# SQL dialect differences between DBI drivers
#
# Every backend agrees on the shape of the schema but disagrees on three
# points: how an auto-incrementing primary key is declared, whether
# `INSERT ... RETURNING` exists, and what has to run right after connecting.
# Each entry below answers those questions for one driver. Anything not
# listed falls back to `ansi`, which probes the connection at runtime.

# The portable baseline. `returning = NA` means "unknown, probe it".
ansi <- list(
  on_connect = character(0),
  pre_ddl = \(table, column) character(0),
  serial_pk = \(table, column) paste(column, "INTEGER PRIMARY KEY"),
  foreign_keys = TRUE,
  fk_cascade = " ON DELETE CASCADE",
  returning = NA,
  last_id = \(table, column) {
    paste0("SELECT MAX(", column, ") AS id FROM ", table)
  }
)

dialects <- list(
  SQLiteConnection = list(
    on_connect = "PRAGMA foreign_keys = ON",
    serial_pk = \(table, column) {
      paste(column, "INTEGER PRIMARY KEY AUTOINCREMENT")
    },
    returning = TRUE,
    last_id = \(table, column) "SELECT last_insert_rowid() AS id"
  ),
  duckdb_connection = list(
    # DuckDB has no AUTOINCREMENT, and it rewrites an UPDATE as a delete plus an
    # insert, so any parent row of a foreign key becomes read-only. Sessions are
    # updated on every answer, so the constraint is dropped rather than the key.
    pre_ddl = \(table, column) {
      paste0("CREATE SEQUENCE IF NOT EXISTS seq_", table)
    },
    serial_pk = \(table, column) {
      paste0(column, " INTEGER PRIMARY KEY DEFAULT nextval('seq_", table, "')")
    },
    foreign_keys = FALSE,
    returning = TRUE,
    last_id = \(table, column) paste0("SELECT currval('seq_", table, "') AS id")
  ),
  PqConnection = list(
    serial_pk = \(table, column) {
      paste(column, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    },
    returning = TRUE,
    last_id = \(table, column) "SELECT lastval() AS id"
  ),
  MariaDBConnection = list(
    serial_pk = \(table, column) {
      paste(column, "INTEGER AUTO_INCREMENT PRIMARY KEY")
    },
    returning = FALSE,
    last_id = \(table, column) "SELECT LAST_INSERT_ID() AS id"
  )
)

dialects$PostgreSQLConnection <- dialects$PqConnection
dialects$MySQLConnection <- dialects$MariaDBConnection

# Returns the dialect for a DBI connection, with each field that the entry
# does not set filled from `ansi`. It matches on the class of the connection,
# so a new driver needs one entry above and no branch at a call site.
dialect_for <- function(con) {
  entry <- dialects[[class(con)[1]]]
  utils::modifyList(ansi, entry %||% list())
}

# Runs the statements that a driver needs right after it connects
on_connect <- function(con) {
  for (statement in dialect_for(con)$on_connect) {
    DBI::dbExecute(con, statement)
  }
  invisible(con)
}
